name: Create Test Environment
on: pull_request

jobs:
  build:
    name: Testing application code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Installing dependencies
        run: pip install -r requirements.txt --target ./packages
        working-directory: app/hello
      - name: Running unit tests
        run: python3 hello_test.py
        working-directory: app/hello

  terraform:
    name: Deploy test AWS infrastructure
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@master
      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.TERRAFORM_BUILD_ROLE }}
          role-duration-seconds: 3600
      - name: Generate temporary worksapce ID
        run: echo "::set-env name=ref_workspace::$(echo ${{ github.ref }} | sha1sum | cut -d' ' -f1 | cut -c -10)"
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: init
          tf_actions_working_dir: .github/terraform
          tf_actions_comment: false
          args: -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" -input=false
      - name: Terraform Plan
        id: terraform_plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: plan
          tf_actions_working_dir: .github/terraform
          tf_actions_comment: false
        env:
          TF_WORKSPACE: ${{ env.ref_workspace }}
      - name: Terraform Apply
        if: steps.terraform_plan.outputs.tf_actions_plan_has_changes == 'true'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: apply
          tf_actions_working_dir: .github/terraform
          tf_actions_comment: false
        env:
          TF_WORKSPACE: ${{ env.ref_workspace }}
      - name: Deploy application to test infra
        run: .github/scripts/deploy_lambda.sh ${{ env.ref_workspace }}-hello-world app/hello