name: Destroy Test Environment
on:
  pull_request:
    types:
      - closed

jobs:
  terraform:
    name: Destroy test AWS infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.TERRAFORM_BUILD_ROLE }}
          role-duration-seconds: 3600
      - name: Generate temporary worksapce ID
        run: echo "::set-env name=ref_workspace::$(git name-rev HEAD --name-only | sha1sum | cut -d' ' -f1 | cut -c -10)"
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: init
          tf_actions_working_dir: .github/terraform
          tf_actions_comment: false
          args: -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" -input=false
      - name: Terraform Destroy
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: destroy
          tf_actions_working_dir: .github/terraform
          tf_actions_comment: false
        env:
          TF_WORKSPACE: ${{ env.ref_workspace }}